import type { AdScript } from '../lib/types'

export const relaxedMenuMenuChaosAr: AdScript = {
  id: 'relaxed-menu-menu-chaos-ar',
  name: 'Relaxed Menu — Arabic Menu Chaos Skit',
  campaign: 'streetmenu-relaxed-menu',
  locale: 'ar',
  direction: 'rtl',
  transitionFrames: 10,
  music: { src: 'audio/menu-chaos-beat.wav', volume: 0.055, fadeOutSeconds: 1.4 },
  narration: { src: 'audio/menu-chaos-ar-voice-smooth-clean.wav', volume: 1 },
  cta: {
    headline: 'وقف إدارة المنيو كأننا في 2005',
    sub: 'عدّل مرة. الكل يشوف التحديث فوراً.',
    button: 'ابدأ مجاناً',
    url: 'relaxedmenu.beyounded.com',
  },
  scenes: [
    {
      id: 'old-paper-menu',
      durationInSeconds: 3.7,
      kicker: 'المشهد ١',
      caption: 'العميل: هذا السعر صحيح؟',
      subCaption: 'صاحب المطعم: لا لا… هذا منيو قديم',
      emphasis: ['قديم'],
      media: { kind: 'placeholder', label: 'Restaurant owner holding printed menus', hint: 'Generate in Kling/Runway: stressed restaurant owner, printed menus everywhere, funny facial expression.' },
      motion: 'punchZoom',
      background: 'cream',
    },
    {
      id: 'sold-out-chaos',
      durationInSeconds: 3.8,
      kicker: 'المشهد ٢',
      caption: 'الزبون: هذا الطبق موجود؟',
      subCaption: 'الجواب المخيف: خلص من أمس 😅',
      emphasis: ['خلص'],
      media: { kind: 'placeholder', label: 'Confused customer at counter', hint: 'Customer points at menu, owner panics, comedic restaurant counter scene.' },
      motion: 'tiltReveal',
      background: 'night',
    },
    {
      id: 'whatsapp-pdf',
      durationInSeconds: 3.7,
      kicker: 'المشهد ٣',
      caption: 'PDF على واتساب… النهائي النهائي v7',
      subCaption: 'وبعدها السعر تغير مرة ثانية',
      emphasis: ['PDF', 'v7'],
      media: { kind: 'placeholder', label: 'WhatsApp PDF chaos', hint: 'Phone screen vibe, many PDF versions, exaggerated notifications.' },
      motion: 'kenBurnsIn',
      background: 'brand',
    },
    {
      id: 'solution-reveal',
      durationInSeconds: 4.0,
      kicker: 'ريلاكسد مينو',
      caption: 'من كيو آر واحد يبدأ الحل',
      subCaption: 'الزبون يمسح ويفتح المنيو المحدث فوراً',
      emphasis: ['كيو آر', 'فوراً'],
      media: { kind: 'qrCard', caption: 'امسح لفتح المنيو' },
      motion: 'riseUp',
      background: 'cream',
    },
    {
      id: 'sold-out-toggle',
      durationInSeconds: 3.9,
      kicker: 'بدون إحراج',
      caption: 'بعدها عدّل السعر أو أخفِ الطبق بثانية',
      subCaption: 'نفس المنيو يتحدث لكل الزبائن',
      emphasis: ['غير متوفر'],
      media: { kind: 'mockMenu', variant: 'soldOut' },
      motion: 'kenBurnsOut',
      background: 'night',
    },
    {
      id: 'cta',
      durationInSeconds: 3.7,
      kicker: 'امسح. شاهد. اطلب.',
      caption: 'ريلاكسد مينو يخلي المنيو يشتغل معاك',
      subCaption: 'مو ضدك',
      emphasis: ['ريلاكسد مينو'],
      media: { kind: 'logo' },
      motion: 'popIn',
      background: 'brand',
      transitionOut: 'none',
    },
  ],
}
